### ISSUE TITLE
missing stelace config

### ISSUE THREAD

**Issue by samjaninf** [stelace/stelace#1]
Want to first say this is awesome love what you guys are building! Hope it goes well.

I spun it up to check it out on my machine and ran into an issue. Following your directions to get everything up and running, Browsersync works fine on port 3001 but Port 3000 just tries to load for a while and then eventually dies and I get this in the command line:
````javascript
info: Starting app...

debug: --------------------------------------------------------
debug: :: Sat Oct 28 2017 19:37:40 GMT-0400 (EDT)
debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
Unhandled rejection Error: No Stelace config available
    at _fetchConfig (/opt/stelace/api/services/StelaceConfigService.js:88:15)
    at <anonymous>

Unhandled rejection Error: No Stelace config available
    at _fetchConfig (/opt/stelace/api/services/StelaceConfigService.js:88:15)
    at <anonymous>
````

Not sure why that is possibly somewhere, sails.config.stelace isn't being called somewhere.

**Comment by woyuen** [comment]
Thank you for your support! The project is moving fast and the documentation is still in progress.

You got this error because some configuration is missing. Please stop the server and try to execute the following scripts from the root of the project:
```
node scripts_migration/createStelaceConfig.js
node scripts_migration/createListingTypes.js
```

After that, you can restart the server.

We'll improve the setup part of the documentation soon ;) This is much needed.

Thank you again!

**Comment by abruere** [comment]
Closed after readme update (https://github.com/stelace/stelace/commit/8fd4b6546a2164079f7f735baa42b58c9b5e6542). Feel free to comment  to reopen if some config is still missing.

Thanks again for feedback!
