### ISSUE TITLE
maps api key should be local.js

### ISSUE THREAD

**Issue by intoku** [stelace/stelace#5]
The setting is missing inside this file

**Comment by woyuen** [comment]
Hi @intoku,

The project settings are split into two locations (the local.js file and the database) because there are two types of settings.

Some settings are not intended to be modified by the administrator (e.g. database connection or email/sms provider data). Those settings are stored into the local.js file.
The other type of settings (e.g. maps api key, language and currency) can be modified and are stored into the database.

As explained here https://github.com/stelace/stelace/issues/4#issuecomment-376476916, the dashboard will allow you to change the second type of settings via a graphical interface.

As it is not ready yet, please follow the instructions below to set the Google maps api key setting:
- into your database, the configuration is stored into the table named `stelaceconfig`
- after the installation, there is only one row in that table
- add the key/value `"google_maps__api_key": "your_api_key"` into the existing object of the column `config`
- restart the server

Thanks for feedback. I close this issue but don't hesitate to post any questions if anything is unclear.
