### ISSUE TITLE
Change "http" in "https" ?

### ISSUE THREAD

**Issue by tereshchuk** [stelace/stelace#597]
tell me how to transfer http to https?

**Comment by woyuen** [comment]
Hi, there's no one-click button that can turn the API from serving http to https requests.

As you didn't describe your architecture, I'll provide you some general guidance on this subject.
Node.js should not handle SSL termination (https requests) directly, because that is a security issue.
Please see this article for more details: https://medium.com/intrinsic/why-should-i-use-a-reverse-proxy-if-node-js-is-production-ready-5a079408b2ca

It's better to handle them with a reverse proxy such as [Nginx](https://nginx.org/en/), [HAProxy](https://www.haproxy.org/) or others.
For free SSL certificates generation, you can use [Let's Encrypt](https://letsencrypt.org/).
There's plenty tutorials on the internet combining a reverse proxy and Let's Encrypt.

I close this issue, but feel free to ask any questions on this conversation.
