### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by tereshchuk** [stelace/stelace#608]
I will try to ask the correct question (I have not been able to resolve this issue for about 2 weeks).
I transferred stelace to a VPS server where nginx and https are installed and the domain name is timosh.com.ua.
Can you tell me what to change in the .env file to make stelace work on my server?
---
P.s: I used to have Stelace on a server without https and nginx and Stelace worked.

----

Do I need to register this data ??

# SSL certificate (common extensions: .crt, .cert, .cer)
# POSTGRES_SSL_CERT =
# Private key (common extension: .key)
# POSTGRES_SSL_KEY =
# Certificate authority (common extensions: .pem, .der)
# POSTGRES_SSL_CA =

And do I need to change
ELASTIC_SEARCH_PROTOCOL = http
on
ELASTIC_SEARCH_PROTOCOL = https

???????????
Help please, I have no one else to ask

**Comment by tereshchuk** [comment]
This error shows me.


<img width="1440" alt="Снимок экрана 2021-03-18 в 18 49 40" src="https://user-images.githubusercontent.com/23060142/111665742-b3fb0880-881b-11eb-868d-77a17365ab7d.png">

**Comment by woyuen** [comment]
First, there is no need to write in bold.
Secondly, you should not change environment variables to make SSL work. The variables you wrote aren't related to this subject.

As @abruere told you, we don't provide support for issues not related to our codebase.
You only need to redirect the requests from the reverse proxy (your Nginx) to the API. That's the most common workflow of APIs serving SSL.
Check your Nginx logs to see where the problem is. And check the docs to see how that works.
