### ISSUE TITLE
Path redis.conf

### ISSUE THREAD

**Issue by tereshchuk** [stelace/stelace#625]
How can I specify the path to the redis.conf file in redis ??
I think it needs to be done in the docker-compose.override.yml file, right ??

Do I need to replace this line?
`
volumes:
      - redis-v5.0.1-data:/data
`
on this:
`
volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
`
or should you leave the old line and add a new line to it ??
`
volumes:
    - redis-v5.0.1-data:/data
    - ./redis.conf:/usr/local/etc/redis/redis.conf
`
????

ps Sorry for bad English((

**Comment by tereshchuk** [comment]
`ауцацауцац`

**Comment by woyuen** [comment]
Hi @tereshchuk, can you tell us why you need to specify a `redis.conf`?

In the case you really need it, I've never tried it but it seems to me you have to keep the two lines.
That's because the current volume `redis-v5.0.1-data:/data` handles Redis data persistence, while the second volume handles configuration.

Did you try your three propositions before asking your questions? It seems not to me.

From my point of view, Github isn't the place where you can ask questions freely and get answers without even trying.
Moreover that's not the first issue you open not to notify a bug or an improvement, but you expect us to help you setup your whole environment.
That's not the purpose of Github issues. As stated by other contributors, hire a consultant for this. That's not our role.

If you don't change the nature of your issues, that will be your last issue I answer.

**Comment by tereshchuk** [comment]
> Hi @tereshchuk, can you tell us why you need to specify a `redis.conf`?
> 
> In the case you really need it, I've never tried it but it seems to me you have to keep the two lines.
> That's because the current volume `redis-v5.0.1-data:/data` handles Redis data persistence, while the second volume handles configuration.
> 
> Did you try your three propositions before asking your questions? It seems not to me.
> 
> From my point of view, Github isn't the place where you can ask questions freely and get answers without even trying.
> Moreover that's not the first issue you open not to notify a bug or an improvement, but you expect us to help you setup your whole environment.
> That's not the purpose of Github issues. As stated by other contributors, hire a consultant for this. That's not our role.
> 
> If you don't change the nature of your issues, that will be your last issue I answer.

ok, sorry for the concern.
