### ISSUE TITLE
User organization and permissions

### ISSUE THREAD

**Issue by izziaraffaele** [stelace/stelace#700]
This is more a question rather than an issue. Is it possible with steleace to have users assigned to organizations and give them the permissions to create/read/update/delete only items within the organization?

**Comment by woyuen** [comment]
Hi @izziaraffaele, thanks for asking this question.
Yes you can do it by customizing the roles for the organization.

By default, an organization is created with the same permissions as normal users, thanks to roles `user`, `provider` and `organization`.
To restrict users within that organization to only perform actions on assets, you can create a custom role that has only the assets permissions as follows:
```js
// POST /roles
{
    name: 'Own assets',
    value: 'own-assets',
    permissions: [
        'asset:list',
        'asset:read',
        'asset:create',
        'asset:edit',
        'asset:remove'
    ]
}
```

And then, you can update the organization to work with this role, so its members will only have the above permissions:
```js
// PATCH /users/:organizationId
{
    roles: [
        'own-assets',
        'organization' // this role is mandatory for organizations
    ]
}
```

Now when you pass the header `x-stelace-organization-id` in addition to user authentication headers, she will only be able to perform actions on assets, but not anymore on listing other users for instance.

Hope it helps.

**Comment by izziaraffaele** [comment]
@woyuen Thanks for the answer! I have two more questions:

1. does this restricts also the search endpoint so that users can only search assets within their organization? 

2. Can you explain to me a little more in detail how those permissions levels interact with each other? I mean... permissions are attached to roles, and roles are attached to users, organizations and to the connection between users with organizations (`user.updateOrganization` route). Let's say that as a user I have the permission `asset:list:all`, the organization has `asset:list` and through the `user.updateOrganization` route I give myself a role inside the organization that has `asset:list:all` permission. How this scenario will play out?

**Comment by woyuen** [comment]
@izziaraffaele, those are good questions:

1. That isn't the case. The permission `search:list:all` won't restrict only on organization assets. Currently there is not such a feature. To be able to filter on a specific organization, you can create a custom attribute where the value is the organization ID and filter on it via the search query.

2. Yes sure. Once the header `x-stelace-organization-id` is passed, the permissions from user roles within organizations will override the user normally attached roles. That's why [the roles specified for the user membership](https://docs.api.stelace.com/#98f4d505-a680-42ba-8d96-62ecb00f8625) are important. The roles can be found in the following path: `user.organizations[organizationId].roles`. However the organizations roles act as boundaries, so even if the user has the superpower `dev` role within her organization, if the organization has only the permission `asset:read` via its roles, the user will only be able to read organization asset and does nothing else with the above header. In your example, your user won't have the permission `asset:list:all` enabled because the organization hasn't it.

**Comment by izziaraffaele** [comment]
@woyuen Crystal clear! Thanks for the explanation!
