### ISSUE TITLE
What is the Document resource for?

### ISSUE THREAD

**Issue by izziaraffaele** [stelace/stelace#708]
This is more a question rather than an issue. Looking at the resources exposed by the API I noticed the Document resource but I couldn't find any documentation about it. 

What are documents? Is it used to store dynamic content tied specifically to a user? What is the target?

**Comment by izziaraffaele** [comment]
Same question for `assessment`

**Comment by woyuen** [comment]
Hi @izziaraffaele, thanks for the questions.

That's exactly what you think. A document is a generic resource that can be used to store any kind of data in a single API object that makes sense for your business.
For context, Document API are used internally by Rating API.
However there is still some work to do, that's why the Document API isn't released yet.

About Assessment API, it is deprecated and can possibly be re-built in the future using the Document API.
The concept was to ensure a transaction went well with some signature mechanism.

**Comment by woyuen** [comment]
I'm closing this issue. Feel free to post additional questions.

**Comment by izziaraffaele** [comment]
Thanks a lot @woyuen for your help!
