### ISSUE TITLE
only 1000 results coming back in search

### ISSUE THREAD

**Issue by bfis108137** [stelace/stelace#750]
We only get 1000 results back in search.  I am assuming this is by design but this is very limiting.  I get that we will never reach the 1000 but we can't actually know how many there even are.  For all we know there could b a million or there could just be 1000

**Comment by woyuen** [comment]
Hi, you cannot retrieve all the results at once and you should use pagination to get them page by page.
This is to counter performance issues, especially with big numbers.

**Comment by bfis108137** [comment]
I don't want all of them at once and we are using pagination.  However, we cannot get more than 1000 results.  That is to say there is no page page 11 when there are 100 per page.  We also would like to know the amount of results even if we are not viewing them.

**Comment by woyuen** [comment]
Ok I see what you mean.
Unfortunately you cannot see the total number of pages, or more precisely it can be a temporary number if there are more than 1000 assets.

That's because the search performs internally two steps: one for relevancy and one for availability.
And to prevent performance issues, assets are considered per batch of 1000.

So you have to look at the response value of the boolean `exhaustiveNbResults`.
If it's `false`, you can increment the `page` from the request even if its value is higher than the temporary `nbPages`.
If it's `true`, the total number of results is the real number.
